In [34]:
import numpy as np

# Matriz de probabilidade de transição


## Cadeias de markov

![imagem](../../imagens/cadeia_de_markov.png)

In [35]:
P = np.matrix('0.7 0.15 0.15; 0.2 0.8 0.15; 0.1 0.5 0.7')
P

matrix([[0.7 , 0.15, 0.15],
        [0.2 , 0.8 , 0.15],
        [0.1 , 0.5 , 0.7 ]])

In [36]:
X_o = np.matrix('0.15; 0.2; 0.65')
X_o

matrix([[0.15],
        [0.2 ],
        [0.65]])

In [37]:
X_1 = P*X_o
X_1

matrix([[0.2325],
        [0.2875],
        [0.57  ]])

Se multiplicra para 10000 pessoas distribuidas:

In [38]:
X_1*10000

matrix([[2325.],
        [2875.],
        [5700.]])

Iésimo estado da cadeia de markov:

![imagem](../../imagens/ex_cadeira_de_markov.png)

In [45]:
n = 3
X_3 = (P**n)*X_o
X_3

matrix([[0.3431625],
        [0.432775 ],
        [0.6063375]])

In [54]:
n = 5
X_5 = (P**n)*X_o
X_5

matrix([[0.45439791],
        [0.58512962],
        [0.76510762]])

In [66]:
n = 10
X_10 = (P**n)*X_o
X_10

matrix([[0.89910916],
        [1.1699616 ],
        [1.50924221]])

In [42]:
n = 15
X_15 = (P**n)*X_o
X_15

matrix([[1.78557153],
        [2.32430306],
        [2.99835809]])

In [43]:
n = 30
X_30 = (P**n)*X_o
X_30

matrix([[13.99729592],
        [18.22060635],
        [23.50479377]])